### PR TITLE
Factor out cmdline, allow for scraping build from source or docker.

### PR DESCRIPTION
**Pull request by kellybyrd**
### Note
With the upcoming HTTP JSON RPC this may not actually be needed, or maybe it's just a step that makes that easier. Regardless, I wanted it working this weekend so I can run for source while keeping the validator metrics. I'll leave it to you if you want to merge it.

### Testing
Works for me. I'm running this right now on skinny-maroon-toad. Validator from source and running this in a systemd service file
```
...
Environment="MINER_PATH=/mnt/data/validator_source/bin/miner"
ExecStart=/opt/helium/miner_exporter/miner_exporter.py
...
```

### Commit Message
Created a new env var MINER_PATH. If it is defined and not empty,
the code will call that in place of the docker module. MINER_PATH
should be the full path to the miner binary, like this:
  MINER_PATH=/opt/miner/bin/miner ./helium_exporter.py

In order to do this, I wrapped the execution in an ExecWrapper
class. It has a run() function that will do either
 `docker_container.exec_run()`
or
 `subprocess.run()`

To make dropping this in easier, `ExecWrapper.run()` has the same
return type as `docker_container.exec_run()`.

Finally, there is some small code reformatting here:
- Reordered the imports because...I couldn't help it

- Whitespace removal in a few places where there either too many
  newlines or just whitespace on an empty line.

### CODE REVIEW

**Comment by kellybyrd** [comment]
I just realized that this new feature will not work at all with docker builds of miner exporter, unless the miner tree is mapped into the miner_exporter container. Probably not worth doing with the http json rpc API coming.

**Comment by tedder** [comment]
Right, that's why I'm kinda dragging my feet :) If the API isn't coming soon I'll put some attention into this, otherwise I'll just leave it open.

**Comment by tedder** [comment]
OTOH the wrapper does set up a way we can subclass and choose docker vs exec. So it's a good path to go down.

**Comment by kellybyrd** [comment]
> Right, that's why I'm kinda dragging my feet :) If the API isn't coming soon I'll put some attention into this, otherwise I'll just leave it open.

> OTOH the wrapper does set up a way we can subclass and choose docker vs exec. So it's a good path to go down.

Yup, no rush!
I'm not sure how much the  JSON RPC calls will map onto the current "exec a thing". I haven't thought a lot about it, but it overall may be better to not try and force the RPC stuff to fit that model. Dunno.

I'm running this myself now, I was going to take a look at adding the JSON RPC support on the next iteration (really waiting for a few more things to show up and the return type to settle)

**Comment by tedder** [comment]
Agree on waiting for the RPC iteration. And .. that they may not match well.

**Comment by kellybyrd** [comment]
Not relevant anymore

**Pull request closed without merging**
